#!/bin/bash

# Sometimes a timeouted QEPCAD instance is not properly killed in realgeom.
# This script supervises to allow only one QEPCAD instance alive.
# Tested on Linux only.

KEEP=2
if [ "$1" != "" ]; then
 KEEP=$1
 fi

while true; do
 RUNNING=`ps uxwwww --sort=start_time | grep qepcad | grep -v tarski | grep -v grep | grep -v keep | wc -l`
 if [ $RUNNING -gt $KEEP ]; then
  DATE=`date`
  echo "$DATE $RUNNING qepcad processes running, 1 will be killed..."
  kill `ps uxwwww --sort=start_time | grep qepcad | grep -v tarski | grep -v grep | grep -v keep | head -1 | awk '{print $2}'`
  fi
 sleep 10
 done
